### ISSUE TITLE
[FEATURE] add meta tags for SEO and social media optimization

### ISSUE THREAD

**Issue by Anmol-Baranwal** [WebXDAO/WebXDAO.github.io#506]
### Detailed description

Several meta tags seem to be missing, and I would like to add these meta tags in the `backup src\pages\index.js` file.

### Context

> For example

```
<meta property="discord:server" content="YOUR_DISCORD_SERVER_ID" />
<meta property="discord:invite" content="YOUR_DISCORD_INVITE_LINK" />
<meta property="discord:site" content="https://discord.com" />
```

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor
